--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  labels:
    app: quote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-container
        image: datawire/quote:0.5.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  selector:
    app: quote-app
  type: NodePort
  ports:
    - name: echo
      port: 8080
      targetPort: 8080
      nodePort: 30076
      protocol: TCP