---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: svelte-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svelte-frontend
  template:
    metadata:
      labels:
        app: svelte-frontend
    spec:
      containers:
      - name: frontend-container
        image: kimschles/frontend:0.0.9
        ports:
        - containerPort: 5173
        env:
        - name: PUBLIC_K8S_SERVICE_URL
          value: "192.168.100.159"
          # value: "http://learning-service.default.svc.cluster.local"
          # value: "Change this value to your backend service URL"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
spec:
  selector:
    app: svelte-frontend
  ports:
    - port: 80
      targetPort: 5173
  type: LoadBalancer