---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev-frontend
  labels:
    app: svelte-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svelte-frontend
  template:
    metadata:
      labels:
        app: svelte-frontend
    spec:
      containers:
      - name: frontend-container
        image: kimschles/frontend:0.0.2
        ports:
        - containerPort: 8080
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev-frontend
spec:
  selector:
    app: svelte-frontend
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP